server:
  port: 8088

spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/demo_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/youhuadb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Yh123$%^
    driver-class-name: com.mysql.jdbc.Driver

#
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # 禁用缓存
  thymeleaf:
    cache: false



mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*Mapper.xml
    typeAliasesPackage: com.youhua.production.bean

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
